---
abstract: 'Catmandu modules for working with OAI repositories'
author:
  - 'Nicolas Steenlant, C<< <nicolas.steenlant at ugent.be> >>'
build_requires:
  Test::Exception: '0.32'
  Test::More: '1.001003'
  Test::Simple: '1.001003'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-OAI
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: '0.9204'
  HTTP::OAI: '4.03'
  IO::Socket::SSL: '1.993'
  Moo: '1.0'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-OAI/issues
  homepage: https://github.com/LibreCat/Catmandu-OAI
  repository: https://github.com/LibreCat/Catmandu-OAI.git
version: '0.04'
x_contributors:
  - 'Jakob Voss <voss@gbv.de>'
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
