---
abstract: 'Catmandu modules for working with OAI repositories'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-OAI
provides:
  Catmandu::Importer::OAI:
    file: lib/Catmandu/Importer/OAI.pm
    version: 0
  Catmandu::OAI:
    file: lib/Catmandu/OAI.pm
    version: 0.01
requires:
  Catmandu: 0.01
  Moo: 0.009011
  Net::OAI::Harvester: 1.13
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
